CREATE TABLE outbox_events (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    processed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attempts TINYINT UNSIGNED DEFAULT 0,
    data TEXT NOT NULL
);